[package]
name = "debate"
version = "0.1.0"
edition = "2024"

[dependencies]
debate-parser = { path = "../debate-parser", version = "0.1.0" }
indent_write = "2.2.0"
lazy_format = "2.0.3"

[features]
default = ["std"]
std = ["debate-parser/std"]
